CREATE TABLE [tbl_Mitglieder] (
  [MitgliedID] AUTOINCREMENT CONSTRAINT [MitgliedID] UNIQUE CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [Mitgliedsnummer] VARCHAR (20) CONSTRAINT [idx_Mitgliedsnummer] UNIQUE,
  [Vorname] VARCHAR (50),
  [Nachname_Name] VARCHAR (100),
  [Titel] VARCHAR (50),
  [Geburtstag] DATETIME,
  [Geschlecht] VARCHAR (20),
  [Mitgliedsgruppe] VARCHAR (50),
  [Mitgliedstyp] VARCHAR (50),
  [Status] VARCHAR (20),
  [Eintrittsdatum] DATETIME,
  [Austrittsdatum] DATETIME,
  [Kündigungsdatum] DATETIME,
  [Ausscheidungsgrund] VARCHAR (100),
  [Email] VARCHAR (100),
  [Telefon] VARCHAR (30),
  [Mobil] VARCHAR (30),
  [Beitrag] CURRENCY,
  [Beitrag_Eingabedatum] DATETIME,
  [Beitragszahlung_Aktiv] BIT,
  [Anmerkungen] LONGTEXT,
  [Created_Date] DATETIME,
  [Created_By] VARCHAR (50),
  [Modified_Date] DATETIME,
  [Modified_By] VARCHAR (50),
  [IsDeleted] BIT
)
